service: tkt-nest

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  stage: production
  region: eu-west-1
  iam:
    role: arn:aws:iam::511810172557:role/fullaccess
functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: "{proxy+}"
          cors: true
