service: tkt-nest

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  stage: production
  region: eu-west-1
  iam:
    role: arn:aws:iam::511810172557:role/fullaccess
functions:
  main:
    handler: dist/main.handler
    environment:
      REGION: eu-west-1
      COGNITO_USER_POOL: eu-west-1_L8K0hML7p
      COGNITO_CLIENT_ID: 629gajnkkbghg3c4965tp0ivuu
    events:
      - http:
          method: ANY
          path: /
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Cognito-Access-Token
              - Cognito-Refresh-Token
              - Cognito-Id-Token
            allowCredentials: false
      - http:
          method: ANY
          path: "{proxy+}"
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Cognito-Access-Token
              - Cognito-Refresh-Token
              - Cognito-Id-Token
            allowCredentials: false
