service: tkt-nest

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  stage: production
  region: eu-west-1

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: "{proxy+}"
